export const FASTSWAP_RECEIVER_ABI = [
  "function relaySwap(bytes data)",
  "function processQueued(bytes32 swapId)",
  "function addLiquidity(address token,uint256 amount) payable",
  "function setLiquidityFloor(address token,uint256 amount)",
  "function adminSweep(address token,address to,uint256 amount)",
  "function aggregateAll(address token,address aggregator,uint256 minReserve,bytes callData) returns (bytes)",
  "function swapState(bytes32 swapId) view returns ((uint8 version,bytes32 quoteId,uint256 sourceChainId,address sourceToken,uint256 sourceAmount,uint256 targetChainId,address targetToken,uint256 targetAmount,address recipient,uint64 expiresAt,address refundAddress),bool requested,bool relayed,bool processed,bool queued,address paidToken,uint256 paidAmount)",
  "function queuedSwapCount() view returns (uint256)",
  "function queuedSwapIdAt(uint256 index) view returns (bytes32)",
  "function liquidityFloor(address token) view returns (uint256)",
  "event SwapRequested(bytes32 indexed swapId,bytes32 indexed quoteId,uint256 indexed targetChainId,address sourceToken,uint256 sourceAmount,address targetToken,uint256 targetAmount,address recipient)",
  "event SwapRelayed(bytes32 indexed swapId,uint256 indexed sourceChainId,address relayer)",
  "event SwapProcessed(bytes32 indexed swapId,address indexed token,address indexed recipient,uint256 amount)",
  "event SwapQueued(bytes32 indexed swapId,address indexed token,uint256 amount)",
] as const;
